# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_hello_world <- function() {
    .Call('_AsCovar_rcpparma_hello_world', PACKAGE = 'AsCovar')
}

rcpparma_outerproduct <- function(x) {
    .Call('_AsCovar_rcpparma_outerproduct', PACKAGE = 'AsCovar', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('_AsCovar_rcpparma_innerproduct', PACKAGE = 'AsCovar', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('_AsCovar_rcpparma_bothproducts', PACKAGE = 'AsCovar', x)
}

timesTwo <- function(x) {
    .Call('_AsCovar_timesTwo', PACKAGE = 'AsCovar', x)
}

